# Generated by Django 4.1.7 on 2023-05-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreC', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=30)),
                ('contra', models.CharField(max_length=30, null=True)),
                ('mail', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('telUsuario', models.IntegerField()),
                ('telCuidador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoPaseador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paseador', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('telUsuario', models.IntegerField()),
                ('telPaseador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('zona', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paseador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('zona', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('emailDueño', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PerroAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('peso', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
                ('zona', models.CharField(max_length=50)),
                ('castrado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=400)),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=30)),
                ('motivo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
