# Generated by Django 4.2.1 on 2023-07-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, default='pendiente', max_length=15, null=True),
        ),
    ]
