# Generated by Django 4.1.7 on 2023-05-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='dni',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paseador',
            name='dni',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
