# Generated by Django 4.2.1 on 2023-07-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=50)),
                ('objetivo', models.IntegerField()),
                ('recaudado', models.IntegerField()),
                ('progreso', models.FloatField()),
            ],
        ),
    ]
