# Generated by Django 4.2.1 on 2023-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroadopcion',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
