# Generated by Django 4.1.7 on 2023-05-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='color',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
