# Generated by Django 4.1.7 on 2023-05-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('telUsuario', models.IntegerField(max_length=50)),
                ('telCuidador', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoPaseador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paseador', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('telUsuario', models.IntegerField(max_length=50)),
                ('telPaseador', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=15)),
                ('zona', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paseador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=15)),
                ('zona', models.CharField(max_length=20)),
                ('disponibilidad', models.CharField(max_length=30)),
            ],
        ),
    ]
