# Generated by Django 4.2.1 on 2023-06-14 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 17, 35, 50, 529879)),
        ),
    ]
