# Generated by Django 4.1.7 on 2023-06-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perroperdido',
            name='telDueño',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
