# Generated by Django 4.2.1 on 2023-05-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perroadopcion',
            name='edad',
        ),
    ]
