# Generated by Django 4.2.1 on 2023-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='castrado',
            field=models.CharField(default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='perro',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
