# Generated by Django 4.2.1 on 2023-05-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='emailDueño',
            field=models.EmailField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
