# Generated by Django 4.1.7 on 2023-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(blank=True, max_length=30, null=True)),
                ('mailD', models.EmailField(blank=True, max_length=30, null=True)),
                ('raza', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha', models.DateField()),
                ('castrado', models.CharField(blank=True, max_length=3, null=True)),
                ('pulsaciones', models.CharField(max_length=30)),
                ('estudios_complementarios', models.CharField(max_length=400)),
                ('diagnostico_presuntivo', models.CharField(max_length=400)),
                ('tratamiento', models.CharField(max_length=400)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
