# Generated by Django 4.1.7 on 2023-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_contactocuidador_contactopaseador_cuidador_paseador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocuidador',
            name='telCuidador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactocuidador',
            name='telUsuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactopaseador',
            name='telPaseador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactopaseador',
            name='telUsuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paseador',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
