# Generated by Django 4.2.1 on 2023-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_cuidador_dni_paseador_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='nombreD',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
