# Generated by Django 4.2.1 on 2023-06-14 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_perro_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='fHoraria',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
