# Generated by Django 4.1.7 on 2023-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_cuidador_dni_paseador_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerroPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('dueño', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
                ('zona', models.CharField(max_length=50)),
                ('fechaD', models.DateTimeField()),
            ],
        ),
    ]
