# Generated by Django 4.2.1 on 2023-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_perro_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='sexo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
