# Generated by Django 4.2.1 on 2023-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_perro_castrado_perro_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perroadopcion',
            name='raza',
            field=models.CharField(max_length=30),
        ),
    ]
