# Generated by Django 4.1.7 on 2023-05-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_perro_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='dniDueño',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
