# Generated by Django 4.2.1 on 2023-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_donacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('mesV', models.IntegerField()),
                ('añoV', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
