# Generated by Django 4.1.7 on 2023-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoadop',
            name='dueño',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
