# Generated by Django 4.1.7 on 2023-06-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_turnos_fhoraria_alter_perro_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='edad',
        ),
    ]
