# Generated by Django 4.2.1 on 2023-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_turnos_fhoraria_alter_perro_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='estado',
            field=models.CharField(blank=True, default='pendiente', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='turnos',
            name='motivoRechazo',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
