# Generated by Django 4.1.7 on 2023-05-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_perro_dnidueño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='dniDueño',
        ),
    ]
