# Generated by Django 4.2.1 on 2023-06-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_perro_nombred'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='perro',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
