# Generated by Django 4.2.1 on 2023-07-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoadop',
            name='dueño',
            field=models.CharField(default='NO', max_length=30),
        ),
    ]
