# Generated by Django 4.2.1 on 2023-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_turnos_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='motivo',
            field=models.CharField(choices=[('1', 'castrar'), ('2', 'vacunar'), ('3', 'Revision'), ('4', 'Otro')], max_length=20),
        ),
    ]
