# Generated by Django 4.1.7 on 2023-06-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_remove_perro_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
