# Generated by Django 4.1.7 on 2023-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerroAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('peso', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=30)),
                ('zona', models.CharField(max_length=50)),
                ('castrado', models.CharField(max_length=2)),
            ],
        ),
    ]
