# Generated by Django 4.2.1 on 2023-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_alter_turnos_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='motivo',
            field=models.CharField(choices=[('castrar', 'castrar'), ('vacunar', 'vacunar'), ('revision', 'Revision'), ('otro', 'Otro')], max_length=20),
        ),
    ]
