# Generated by Django 4.1.7 on 2023-05-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_nombre_cliente_nombrec_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contra',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
