# Generated by Django 4.2.1 on 2023-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_alter_turnos_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='onLine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='perro',
            field=models.CharField(max_length=100),
        ),
    ]
