# Generated by Django 4.1.7 on 2023-05-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_alter_cliente_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
    ]
