# Generated by Django 4.2.1 on 2023-05-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_turnos_fecha_alter_turnos_motivo'),
        ('APP', '0009_remove_cliente_dni'),
    ]

    operations = [
    ]
