# Generated by Django 4.2.1 on 2023-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_alter_turnos_edad_alter_turnos_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='raza',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
