# Generated by Django 4.2.1 on 2023-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_alter_cliente_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=30)),
                ('mailD', models.EmailField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.BooleanField()),
                ('descripcion', models.TextField(max_length=400)),
                ('motivo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('castrado', models.BooleanField(default=False)),
                ('color_pelo', models.CharField(max_length=30)),
                ('pulsaciones', models.CharField(max_length=30)),
                ('estudios_complementarios', models.TextField(max_length=400)),
                ('diagnostico_presuntivo', models.TextField(max_length=400)),
                ('tratamiento', models.TextField(max_length=400)),
                ('proxima_visita', models.DateField()),
            ],
        ),
    ]
