# Generated by Django 4.2.1 on 2023-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='historial',
            name='diagnostico_presuntivo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='historial',
            name='estudios_complementarios',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tratamiento',
            field=models.CharField(max_length=400),
        ),
    ]
